config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "talents#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :talents do
    resources :bookings, only: %i[new create]
  end

  resources :booking, only: [] do
    resources :reviews, only: %i[new create]
  end

  resources :bookings, only: %i[destroy]
  get "dashboard", to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :talent
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :comment, presence: true, length: { minimum: 6 }
  validates :rating, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 5
  }
end

app/models/talent.rb
class Talent < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  belongs_to :user
  has_many_attached :medias

  validates :pseudo, presence: true
  validates :working_area, presence: true
  validates :talent_type, presence: true
  validates :price, presence: true
  validates :performance_duration, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :talents, dependent: :destroy
  has_one_attached :profile_picture

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :password, presence: true
  validates :sex, presence: true
  before_validation :validate_age

  private

  def validate_age
    if date_of_birth.present? && date_of_birth.year > 2005
      errors.add(:date_of_birth, 'You should be over 18 years old.')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :date_of_birth, :sex, :address, :phone, :description, :profile_picture])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :date_of_birth, :sex, :address, :phone, :description, :profile_picture])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    if user_signed_in?
      @booking = Booking.new(booking_params)
      @talent = Talent.find(params[:talent_id])
      @booking.talent = @talent
      @booking.user = current_user
      if @booking.save
        redirect_to dashboard_path, notice: 'Booking was successfully created.'
      else
        # Handle validation errors or other cases where the booking couldn't be saved
        redirect_to talent_path, alert: 'Booking could not be created.'
      end
    else
      redirect_to new_user_session_path, alert: 'Please sign in to book a freak.'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :address, :talent_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @user = current_user
    @review = Review.new
    @talents = @user.talents
    @booked_talent = @user.bookings.includes(:talent).map(&:talent)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    if @review.save
      redirect_to dashboard_path
    else
      redirect_to dashboard_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating, :booking_id)
  end
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_talent, only: %i[show edit update destroy]

  def show
    @booking = Booking.new
    @bookings = @talent.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to: booking.end_date
      }
    end
    @user = @talent.user
  end

  def new
    @talent = Talent.new
  end

  def index
    @talents = Talent.all
    if params[:talent_type].present?
      @talents = @talents.where(talent_type: params[:talent_type])
    end
    if params[:query].present?
      @talents = @talents.where("working_area ILIKE ?", "%#{params[:query]}%")
    end
  end

  def create
    @talent = Talent.new(talent_params)
    @talent.user = current_user
    if @talent.save
      redirect_to talent_path(@talent)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @talent.update(talent_params)
      redirect_to talent_path(@talent)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @talent.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def set_talent
    @talent = Talent.find(params[:id])
  end

  def talent_params
    params.require(:talent).permit(:pseudo, :working_area, :talent_type, :price, :performance_duration, :description, medias: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to talents_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    raise
  end
  def update
    if @user.update(user_params)
      raise
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to talents_path, status: :see_other
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :sex, :date_of_birth, :phone, :description, :address, :profile_picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Louetonchelou</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('mimi.jpeg') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@600;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container mt-4">
      <div style="min-height: 84vh"><%= yield %></div>
    </div>
    <%= render "shared/flashes" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <ul class="list-inline tabs-underlined" id="myTab" role="tablist">
    <li role="presentation">
      <a href="#" class="tab-underlined active" id="booking-tab" data-bs-toggle="tab" data-bs-target="#booking" role="tab" aria-controls="booking" aria-selected="true">Bookings</a>
    </li>
    <li role="presentation">
      <a href="#" class="tab-underlined" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" role="tab" aria-controls="profile" aria-selected="false">Profile</a>
    </li>
    <% if @user.talents.any? %>
    <li role="presentation">
      <a href="#" class="tab-underlined" id="talent-tab" data-bs-toggle="tab" data-bs-target="#talent" role="tab" aria-controls="talent" aria-selected="false">Talents</a>
    </li>
    <% else %>
    <% end %>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="booking" role="tabpanel" aria-labelledby="booking-tab">
      <% if @user.bookings.count > 1 %>
        <h2>Your bookings <%= @user.first_name %></h2>
      <% else %>
        <h2>Your booking <%= @user.first_name %></h2>
      <% end %>
      <% @user.bookings.each do |booking| %>
        <div class="card-booking">
          <% if booking.talent.medias.attached?  %>
            <img src="<%= cl_image_path(booking.talent.medias.first.key)%>" class="card-img-top" alt="Talent picture">
          <% else %>
            <img src="<%= asset_path('mimi.jpeg')%>" class="card-img-top" alt="Talent picture">
          <% end %>
          <div class="card-booking-infos">
            <h2><%= link_to booking.talent.pseudo.capitalize, talent_path(booking.talent), class: "colored-link" %> - <%= link_to booking.talent.talent_type.capitalize, talent_path(booking.talent), class: "colored-link" %></h2>
            <p>Description: <%= booking.talent.description %></p>
            <p>From <%= booking.start_date %> to <%= booking.end_date %> - <%= booking.address %></p>
            <p>Price: <%= number_with_precision(booking.talent.price, precision: 2) %> €</p>
            <i class="fa-solid fa-pen-nib"></i><%= link_to "Write a Review", new_booking_review_path(booking), class: 'light-link', 'data-bs-toggle' => 'modal', 'data-bs-target' => "#review_popup#{booking.talent.id}" %> <span class='light-link'>|</span>
            <i class="fa-regular fa-circle-xmark"></i><%= link_to "Cancel your booking", booking_path(booking), class: 'light-link', data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel this booking with #{booking.talent.pseudo}?" } %>
          </div>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="review_popup<%= booking.talent.id %>" tabindex="-1" aria-labelledby="review_popup<%= booking.talent.id %>Label" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="review_popup<%= booking.talent.id %>Label">Write a Review for your booking with <%= booking.talent.pseudo %> </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <%= simple_form_for [booking, @review] do |f| %>
                  <%= f.input :comment, placeholder: "Add your review here..." %>
                  <%= f.input :rating, as: :select, collection: (1..5), required: true %>
                  <%= f.submit class: "btn btn-flat" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to "Book another talent", root_path, class: "btn btn-flat" %>
      <% if @user.talents.any? %>
      <% else %>
        <%= link_to "Wanna become a chelou?", new_talent_path, class: "btn btn-flat" %>
      <% end %>
    </div>

    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="row">
        <div class="left-container">
          <div class="inter-left">
            <div class="white-block">
              <div class="left-side">
                <img class="avatar" src="<%= current_user && current_user.profile_picture.attached? ? cl_image_path(current_user.profile_picture.key) :asset_path('mimi.jpeg') %>" alt="">
                <h4><%= current_user.first_name %></h4>
              </div>
              <div class="right-side">
                <p class="number"><%= @user.bookings.count %></p>
                <% if @user.bookings.count > 1 %>
                  <p>bookings</p>
                <% else %>
                  <p>booking</p>
                <% end %>
                <hr>
                <p class="number"><%= @user.talents.count %></p>
                <% if @user.talents.count > 1 %>
                  <p>talents</p>
                <% else %>
                  <p>talent</p>
                <% end %>
              </div>
            </div>
            <%= link_to "Edit my profile", edit_user_registration_path, class: "btn btn-flat" %>
          </div>
        </div>
        <div class="right-container">
          <h2>Your account</h2>
          <div class="card-profile">
            <div class="card-data">
              <h5>Name</h5>
              <p><%= @user.first_name %> <%= @user.last_name %></p>
            </div>
            <div class="card-data">
              <h5>Email</h5>
              <p><%= @user.email %></p>
            </div>
            <div class="card-data">
              <h5>Date of Birth</h5>
              <p><%= @user.date_of_birth %></p>
            </div>
            <div class="card-data">
              <h5>Sex</h5>
              <p><%= @user.sex.capitalize %></p>
            </div>
            <div class="card-data">
              <h5>Address</h5>
              <p><%= @user.address %></p>
            </div>
            <div class="card-data">
              <h5>Phone</h5>
              <p><%= @user.phone %></p>
            </div>
            <div class="card-data">
              <h5>Description</h5>
              <p><%= @user.description %></p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="tab-pane fade" id="talent" role="tabpanel" aria-labelledby="talent-tab">
      <% if @user.talents.count > 1 %>
        <h2>Your talents <%= @user.first_name %></h2>
      <% else %>
        <h2>Your talent <%= @user.first_name %></h2>
      <% end %>
      <% @user.talents.each do |talent| %>
        <div class="card-booking">
          <% if talent.medias.attached?  %>
            <img src="<%= cl_image_path(talent.medias.first.key)%>" class="card-img-top" alt="Talent picture">
          <% else %>
            <img src="<%= asset_path('mimi.jpeg')%>" class="card-img-top" alt="Talent picture">
          <% end %>
          <div class="card-booking-infos">
            <h2><%= link_to talent.talent_type.capitalize, talent_path(talent), class: "colored-link" %> - <%= link_to talent.working_area, talent_path(talent), class: "colored-link" %></h2>
            <p>Description: <%= talent.description %></p>
            <p>Performance duration: <%= talent.performance_duration %></p>
            <p>Price: <%= number_with_precision(talent.price, precision: 2) %> €</p>
            <i class="fa-solid fa-wand-magic-sparkles baguette"></i><%= link_to "Edit your talent", edit_talent_path(talent), class: 'light-link' %> <span class='light-link'>|</span>
            <i class="fa-regular fa-circle-xmark"></i><%= link_to "Remove your talent", talent_path(talent), class: 'light-link', data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove this talent?" } %>
          </div>
        </div>
      <% end %>
      <h2>Your upcoming shows</h2>
      <% @talents.each do |talent| %>
        <% talent.bookings.each do |booking| %>
          <div class="card-booking">
            <div class="card-booking-infos">
              <h2><%= booking.start_date %> to <%= booking.end_date %> | <%= booking.address %></h2>
              <p>Performance: <%= link_to booking.talent.talent_type, talent_path(booking.talent), class: "colored-link" %></p>
              <p>Customer contact: <%= booking.user.first_name %> <%= booking.user.last_name %> | <%= booking.user.phone %></p>
              <p>Price: <%= number_with_precision(booking.talent.price, precision: 2) %> €</p>
              <i class="fa-regular fa-circle-xmark"></i><%= link_to "Cancel your booking", booking_path(booking), class: 'light-link', data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to cancel this booking with #{booking.user.first_name}?" } %>
            </div>
          </div>
        <% end %>
      <% end %>
      <h2>Your reviews</h2>
      <% @talents.each do |talent| %>
        <% talent.bookings.each do |booking| %>
          <% booking.reviews.each do |review| %>
            <div class="card-review">
              <i class="fa-solid fa-star"></i><p><%= review.rating %>/5 "<%= review.comment %>"</p>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <%# <p>You don't have any review yet. Come back later!</p> %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Write a Review</h1>

<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :comment, placeholder: "Add your review here..." %>
  <%= f.input :rating, as: :select, collection: (1..5), required: true, label: false %>
  <%= f.submit class: "btn" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="border-top">
  <div class="footer-content d-flex justify-content-between px-4 pt-2">
    <div class="left-content">
      <i class=“fa-solid fa-democrat”></i>
      <p>&copy; 2023 Loue ton Chelou</p>
    </div>
    <div class="right-content">
      <a href="https://www.instagram.com/lovely.freaksss/" target="_blank"><i class="fab fa-instagram"></i></a>
      <a href="https://github.com/danarasta12/louetonchelou" target="_blank"><i class="fab fa-github"></i></a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-democrat" id="democrat" style="font-size: 40px"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav d-flex">

        <% if user_signed_in? %>

          <div>
            <li class="nav-item" id="freak">
              <%= link_to "Wanna become a chelou?", new_talent_path, class: "nav-link" %>
            </li>
          </div>


          <div class="burger-menu">
            <li class="nav-item dropdown">
                <i class="fa-solid fa-burger dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
                <img class="avatar" src="<%= current_user.profile_picture.present? ? cl_image_path(current_user.profile_picture.key) :asset_path('mimi.jpeg') %>" alt="">
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          </div>


        <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>

        <% end %>

      </ul>

    </div>

  </div>
</div>

app/views/talents/edit.html.erb
<%= simple_form_for @talent do |f| %>
  <%= f.input :pseudo %>
  <%= f.input :working_area, collection: [["Paris (75)", "75"], ["Hauts-de-Seine (92)", "92"], ["Seine-Saint-Denis (93)", "93"], ["Val-de-Marne (94)", "94"], ["Seine-et-Marne (77)", "77"], ["Yvelines (78)", "78"], ["Essonne (91)", "91"], ["Val-d'Oise (95)", "95"]], include_blank: "Select Working Area", label_method: :first, value_method: :last %>
  <%= f.input :talent_type, as: :select, collection: ['Magicien', 'Cracheur de Feu', 'Dompteur de Serpent', 'Stripteaseur', 'Clown'], include_blank: "Select Talent type" %>
  <%= f.input :price %>
  <%= f.input :performance_duration %>
  <%= f.input :medias, as: :file, input_html: { multiple: true } %>
  <%= f.input :description, as: :text %>

  <%= f.button :submit, class: "btn btn-flat" %>
<% end %>

app/views/talents/index.html.erb
<section class="search-filters">
  <div class="talent-filters" id="test">

      <div>
        <%= form_with url: talents_path, method: :get, class: "d-flex" do %>

          <label for="all"><i class="fa-solid fa-democrat fa-2x icon curseur"></i><span class="span-opacity">All</span></label>
          <%= radio_button_tag :talent_type, "", false, id: 'all', hidden: true %>

          <label for="magicien"><i class="fa-solid fa-wand-magic-sparkles fa-2x icon curseur"></i><span class="span-opacity">Magicien</span></label>
          <%= radio_button_tag :talent_type, "Magicien", false, id: 'magicien', hidden: true %>

          <label for="clown"><i class="fa-solid fa-face-grin-squint-tears fa-2x icon curseur"></i><span class="span-opacity">Clown</span></label>
          <%= radio_button_tag :talent_type, "Clown", false, id: 'clown', hidden: true %>

          <label for="cracheur"><i class="fa-solid fa-fire fa-2x icon curseur"></i><span class="span-opacity">Cracheur Feu</span></label>
          <%= radio_button_tag :talent_type, "Cracheur de Feu", false, id: 'cracheur', hidden: true %>

          <label for="dompteur"><i class="fa-solid fa-staff-snake fa-2x icon curseur"></i><span class="span-opacity">Dompteur Serpents</span></label>
          <%= radio_button_tag :talent_type, "Dompteur de Serpents", false, id: 'dompteur', hidden: true %>

          <label for="strip"><i class="fa-solid fa-venus fa-2x icon curseur"></i><span class="span-opacity">Striptease</span></label>
          <%= radio_button_tag :talent_type, "Stripteaseur", false, id: 'strip', hidden: true %>

          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "ex: 75" %>

          <button type="submit" class="btn btn-index">
            <i class="fa-solid fa-magnifying-glass"></i>
          </button>
        <% end %>
      </div>

  </div>
</section>

<section class="talent-list">
  <div class="row">
    <% @talents.each do |talent| %>
      <div class="col-md-3 talent-card">
        <a href="<%= talent_path(talent) %>" class="card-link" style="text-decoration: none">
          <div class="card">
            <% if talent.medias.attached?  %>
              <img src="<%= cl_image_path(talent.medias.first.key)%>" class="card-img-top" alt="Talent picture">
            <% else %>
              <img src="<%= asset_path('mimi.jpeg')%>" class="card-img-top" alt="Talent picture">
            <% end %>

            <div class="card-body">
              <h5 class="card-title"><%= talent.pseudo %></h5>
              <p class="card-text"><%= talent.talent_type %> - <%= talent.working_area %></p>

              <div class="price-rating">
                <p><%= number_with_precision(talent.price, precision: 2) %> €</p>

                <% if talent.reviews.any? %>
                  <% total_ratings = talent.reviews.pluck(:rating).compact.sum %>
                  <% average_rating = total_ratings.to_f / talent.reviews.count %>
                  <p> <%= average_rating.round(2) %> <i class="fa-solid fa-star"></i></p>
                <% else %>
                  <p> No rating yet </p>
                <% end %>

              </div>

            </div>
          </div>

        </a>

      </div>

    <% end %>

  </div>
</section>

app/views/talents/new.html.erb
<div class="registration-form-container">
  <h2>Become a Chelou</h2>

  <%= simple_form_for @talent do |f| %>
    <div class="form-group">
      <%= f.input :pseudo, class: "form-control", placeholder: "Jeannot le rigolo" %>
    </div>

    <div class="form-group row">
      <div class="col">
        <%= f.input :price, class: "form-control", input_html: { min: '0', step: 'any' }, :wrapper_html => { :style => 'display: inline' } %>
      </div>

      <div class="col">
        <%= f.input :performance_duration, class: "form-control", :wrapper_html => { :style => 'display: inline' } %>
      </div>
    </div>
    <br>
    <div class="form-group">
      <%= f.input :working_area, collection: [["Paris (75)", "75"], ["Hauts-de-Seine (92)", "92"], ["Seine-Saint-Denis (93)", "93"], ["Val-de-Marne (94)", "94"], ["Seine-et-Marne (77)", "77"], ["Yvelines (78)", "78"], ["Essonne (91)", "91"], ["Val-d'Oise (95)", "95"]], include_blank: "Select Working Area", class: "form-select", label_method: :first, value_method: :last, label: false %>
    </div>

    <div class="form-group">
      <%= f.input :talent_type, collection: ['Magicien', 'Cracheur de Feu', 'Dompteur de Serpent', 'Stripteaseur', 'Clown'], include_blank: "Select Talent type", class: "form-select", label: false %>
    </div>


    <div class="form-group">
      <%= f.label :medias, "Medias" %>
      <%= f.file_field :medias, multiple: true, class: "form-control-file" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <%= f.submit "Submit", class: "btn btn-flat w-100" %>
  <% end %>
</div>